name: Publish Docker ARM64 and AMD64
on:
  push:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Run Buildx AMD64
        run: |
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
          docker buildx build \
                      --platform linux/amd64 \
                      -t docker.pkg.github.com/singproapp/singpro-fe/amd64:latest \
                      --load .
      - name: push Buildx AMD64
        run: |
          docker push docker.pkg.github.com/singproapp/singpro-fe/amd64:latest
